### ISSUE TITLE
CUDA out of memory.如何处理呢？

### ISSUE THREAD

**Issue by chenmaolin1** [autonomousvision/mip-splatting#62]
RuntimeError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 23.79 GiB total capacity; 20.60 GiB already allocated; 38.38 MiB free; 20.60 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by niujinshuchong** [comment]
Hi, which dataset are you testing and when the OOM happens?

**Comment by chenmaolin1** [comment]
Environment: GPU 24GB video memory

**Comment by niujinshuchong** [comment]
Hi, maybe the image is of too high resolution, and more Gaussians are allocated. Could you try to use factor 2 of 4?

**Comment by chenmaolin1** [comment]
There was no problem trying factor 2 and 4.  But if factor is 1, does OOM solve fang? thank you

**Comment by niujinshuchong** [comment]
Hi,could you compare the number of Gaussians in these cases?

**Comment by chenmaolin1** [comment]
Sorry, I don't know where to look at the number of Gaussians , I don't know very well.thank you.

**Comment by chenmaolin1** [comment]
I've fixed the problem, and setting factor to -1 will stop oom from appearing. Thank you.
